version: 2.1

jobs:
  hello:
    machine: true
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run:
          name: greeting
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/src
            python main.py
  build:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run:
          name: show version
          command: |
            docker version
      - run:
          name: build docker image
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            docker build . -t chowntest
      - run:
          name: check
          command: |
            docker run chowntest ls / -al

workflows:
  version: 2
  build:
    jobs:
      - build
