version: 2.1

jobs:
  hello:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: greeting
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/src
            python main.py

workflows:
  version: 2
  hello-work:
    jobs:
      - hello
