version: 2.1

jobs:
  hello:
    machine:
      docker_layer_caching: true
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run:
          name: greeting
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/src
            python main.py

workflows:
  version: 2
  hello-work:
    jobs:
      - hello
