version: 2.1

jobs:
  hello:
    machine: true
    steps:
      - checkout
      - run:
          name: greeting
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/src
            python main.py

workflows:
  version: 2
  hello-work:
    jobs:
      - hello
